apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: default.projects.pkg.platformnow.io
  labels:
    crossplane.io/xrd: projects.pkg.platformnow.io
spec:
  compositeTypeRef:
    apiVersion: pkg.platformnow.io/v1
    kind: Project
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-project-provider-k8s-pc-in"
      readinessChecks:
        - type: None
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          namespace: landscape-system
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "%s-namespace"
          toFieldPath: metadata.name
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
        - fromFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-project-provider-k8s-pc-in"
          toFieldPath: spec.providerConfigRef.name
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          namespace: landscape-system
        spec:
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: AppProject
              metadata:
                namespace: landscape-system
              spec:
                clusterResourceWhitelist:
                  - group: '*'
                    kind: '*'
                destinations:
                  - name: '*'
                    namespace: '*'
                    server: https://kubernetes.default.svc
                namespaceResourceWhitelist:
                  - group: '*'
                    kind: '*'
                sourceNamespaces:
                  - "*"
                sourceRepos:
                  - '*'
      patches:
        - fromFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-argo-project"
          toFieldPath: metadata.name
        - fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
        - fromFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-project-provider-k8s-pc-in"
          toFieldPath: spec.providerConfigRef.name
